package sdkgen

import (
	"fmt"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/projectluojia/AI-Luo-Man-ga/package-manager/pkg/capability"
)

// emitTypeScript 渲染 TypeScript SDK：client.ts，包含传输层与每个 capability
// 的类型化方法（async/await + fetch 标准 API，仅浏览器/Deno 运行时）。
func emitTypeScript(packageID string, capabilities []capability.CapabilitySpec, models map[string]*TypeModel) []Generated {
	var builder strings.Builder
	pkgName := packageName(packageID)
	fmt.Fprintf(&builder, "// Code generated by ailuo sdkgen. DO NOT EDIT.\n//\n// Source: %s\n\n", packageID)
	// 所有类型定义（interface / union type），置于 class 之前。
	for _, capability := range capabilities {
		for _, namedModel := range collectNamed(models[capability.ID]) {
			switch namedModel.Kind {
			case KindEnum:
				tsUnionType(&builder, namedModel)
			case KindObject:
				tsInterface(&builder, namedModel)
			}
		}
	}
	// Client class：构造 + invoke 传输层 + 每 capability 方法。
	builder.WriteString(tsClientTypes)
	fmt.Fprintf(&builder, "export class %sClient {\n", strcase.ToCamel(pkgName))
	builder.WriteString(strings.ReplaceAll(tsClientTemplate, "{Q}", "`"))
	for _, capability := range capabilities {
		tsCapability(&builder, capability, models[capability.ID], packageID)
	}
	builder.WriteString("}\n")
	return []Generated{{Path: pkgName + "/client.ts", Code: []byte(builder.String())}}
}

// tsCapability 渲染一个 capability 的类型化方法（与 goCapability/pythonCapability 对称）。
func tsCapability(builder *strings.Builder, capability capability.CapabilitySpec, model *TypeModel, packageID string) {
	name := tsMethodName(capability.ID, packageID)
	// 根 schema 可能是标量（具名类型的 Name 才非空），故经 tsFieldType 映射。
	fmt.Fprintf(builder, "  %s(input: %s, options?: CallOptions): Promise<unknown> {\n", name, tsFieldType(model))
	fmt.Fprintf(builder, "    return this.invoke(%q, input, options);\n", capability.ID)
	builder.WriteString("  }\n\n")
}

// tsClientTemplate 是 Client 构造与 invoke 传输层模板；{Q} 渲染时替换为反引号
// （TypeScript 模板字符串语法，Go 反引号字符串无法直接承载）。
const tsClientTypes = `export interface CallOptions {
  idempotencyKey?: string;
  confirmationId?: string;
}

export type HeaderProvider = (capabilityId: string) => HeadersInit;

export interface ClientOptions {
  headers?: HeadersInit;
  headerProvider?: HeaderProvider;
}

export class InvokeError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    public readonly message: string,
    public readonly retryable: boolean,
  ) {
    super(message);
    this.name = "InvokeError";
  }
}

`

const tsClientTemplate = `  private baseUrl: string;
  private options: ClientOptions;
  constructor(baseUrl: string, options: ClientOptions = {}) {
    this.baseUrl = baseUrl.replace(/\/+$/, "");
    this.options = options;
  }

  private async invoke(capabilityId: string, input: unknown, options?: CallOptions): Promise<unknown> {
    const headers = new Headers(this.options.headers);
    headers.set("Content-Type", "application/json");
    if (this.options.headerProvider !== undefined) {
      new Headers(this.options.headerProvider(capabilityId)).forEach((value, name) => headers.set(name, value));
    }
    if (options?.idempotencyKey !== undefined) {
      headers.set("Idempotency-Key", options.idempotencyKey);
    }
    if (options?.confirmationId !== undefined) {
      headers.set("X-Confirmation-ID", options.confirmationId);
    }
    const response = await fetch({Q}${this.baseUrl}/api/v1/capabilities/${capabilityId}/invoke{Q}, {
      method: "POST",
      headers,
      body: JSON.stringify({ input }),
    });
    const body = await response.text();
    if (!response.ok) {
      let parsed: unknown;
      try {
        parsed = JSON.parse(body);
      } catch {
        throw new InvokeError(response.status, "invalid_response", "服务端错误响应格式无效", false);
      }
      if (typeof parsed !== "object" || parsed === null ||
          typeof (parsed as { code?: unknown }).code !== "string" ||
          typeof (parsed as { message?: unknown }).message !== "string") {
        throw new InvokeError(response.status, "invalid_response", "服务端错误响应格式无效", false);
      }
      const errorBody = parsed as { code: string; message: string; retryable?: unknown };
      throw new InvokeError(response.status, errorBody.code, errorBody.message, errorBody.retryable === true);
    }
    let envelope: unknown;
    try {
      envelope = JSON.parse(body);
    } catch {
      throw new InvokeError(response.status, "invalid_response", "服务端成功响应格式无效", false);
    }
    if (typeof envelope !== "object" || envelope === null || !("result" in envelope)) {
      throw new InvokeError(response.status, "invalid_response", "服务端成功响应格式无效", false);
    }
    return envelope.result;
  }

`

// tsInterface 渲染 object 为 interface（字段用 JSON key 名，可选加 ?）。
func tsInterface(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "export interface %s {\n", model.Name)
	for _, field := range model.Fields {
		opt := ""
		if !field.Required {
			opt = "?"
		}
		fmt.Fprintf(builder, "  %s%s: %s;\n", field.Name, opt, tsFieldType(field.Type))
	}
	builder.WriteString("}\n\n")
}

// tsUnionType 渲染 enum 为 union type。
func tsUnionType(builder *strings.Builder, model *TypeModel) {
	values := make([]string, 0, len(model.Values))
	for _, value := range model.Values {
		values = append(values, fmt.Sprintf("%q", value))
	}
	fmt.Fprintf(builder, "export type %s = %s;\n\n", model.Name, strings.Join(values, " | "))
}

// tsFieldType 映射字段类型注解。可选性由 interface 属性级 ?（见 tsInterface）表达，
// 故无 required 参数。
func tsFieldType(model *TypeModel) string {
	switch model.Kind {
	case KindString:
		return "string"
	case KindInteger, KindNumber:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindDateTime:
		return "Date"
	case KindEnum, KindObject:
		return model.Name
	case KindArray:
		return tsFieldType(model.Elem) + "[]"
	default:
		return "unknown"
	}
}
