package sdkgen

import (
	"fmt"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/projectluojia/AI-Luo-Man-ga/contracts/pkg/capability"
)

// emitGo 渲染 Go SDK：一个 client.go，包含传输层与每个 capability 的类型化方法。
func emitGo(packageID string, capabilities []capability.CapabilitySpec, models map[string]*TypeModel) []Generated {
	var builder strings.Builder
	fmt.Fprintf(&builder, "// Code generated by ailuo sdkgen. DO NOT EDIT.\n//\n// Source: %s\npackage %s\n\n", packageID, packageName(packageID))
	builder.WriteString(strings.ReplaceAll(goClient, "{Q}", "`"))
	for _, capability := range capabilities {
		goCapability(&builder, capability, models[capability.ID], packageID)
	}
	return []Generated{{Path: packageName(packageID) + "/client.go", Code: []byte(builder.String())}}
}

const goClient = `import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// HeaderProvider 在发送请求前注入认证材料；实现不得把凭据写入日志。
type HeaderProvider func(context.Context, *http.Request) error

// ClientOption 配置消费方客户端。
type ClientOption func(*Client)

// CallOption 配置一次 Capability 调用的治理字段。
type CallOption func(*callOptions)

type callOptions struct {
	IdempotencyKey string
	ConfirmationID string
}

// WithHeaderProvider 注入认证或其他受信请求头。
func WithHeaderProvider(provider HeaderProvider) ClientOption {
	return func(client *Client) { client.headerProvider = provider }
}

// WithIdempotencyKey 为写入或外部副作用调用设置幂等键。
func WithIdempotencyKey(value string) CallOption {
	return func(options *callOptions) { options.IdempotencyKey = value }
}

// WithConfirmationID 为需要确认的调用设置已批准确认标识。
func WithConfirmationID(value string) CallOption {
	return func(options *callOptions) { options.ConfirmationID = value }
}

// Error 是 invoke 端点返回的稳定结构化错误。
type Error struct {
	Status    int
	Code      string
	Message   string
	Retryable bool
}

func (e *Error) Error() string {
	return fmt.Sprintf("ailuo invoke failed: HTTP %d %s: %s", e.Status, e.Code, e.Message)
}

// Client 调用内核 capability，经 invoke 端点（POST /api/v1/capabilities/{id}/invoke）。
type Client struct {
	baseURL        string
	http           *http.Client
	headerProvider HeaderProvider
}

// NewClient 构造消费方客户端。
func NewClient(baseURL string, options ...ClientOption) *Client {
	client := &Client{baseURL: strings.TrimRight(baseURL, "/"), http: &http.Client{Timeout: 30 * time.Second}}
	for _, option := range options {
		if option != nil {
			option(client)
		}
	}
	return client
}

// invoke 是最小传输信封：{"input": <payload>} → {"result": <value>}。
func (c *Client) invoke(ctx context.Context, capabilityID string, input any, options ...CallOption) (json.RawMessage, error) {
	call := callOptions{}
	for _, option := range options {
		if option != nil {
			option(&call)
		}
	}
	payload, err := json.Marshal(struct {
		Input any {Q}json:"input"{Q}
	}{Input: input})
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost,
		c.baseURL+"/api/v1/capabilities/"+url.PathEscape(capabilityID)+"/invoke", bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	request.Header.Set("Content-Type", "application/json")
	if c.headerProvider != nil {
		if err := c.headerProvider(ctx, request); err != nil {
			return nil, err
		}
	}
	if call.IdempotencyKey != "" {
		request.Header.Set("Idempotency-Key", call.IdempotencyKey)
	}
	if call.ConfirmationID != "" {
		request.Header.Set("X-Confirmation-ID", call.ConfirmationID)
	}
	response, err := c.http.Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	body, err := io.ReadAll(io.LimitReader(response.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if response.StatusCode != http.StatusOK {
		var apiError struct {
			Code      string {Q}json:"code"{Q}
			Message   string {Q}json:"message"{Q}
			Retryable bool   {Q}json:"retryable"{Q}
		}
		if err := json.Unmarshal(body, &apiError); err != nil || apiError.Code == "" {
			return nil, &Error{Status: response.StatusCode, Code: "invalid_response", Message: "服务端错误响应格式无效"}
		}
		return nil, &Error{Status: response.StatusCode, Code: apiError.Code, Message: apiError.Message, Retryable: apiError.Retryable}
	}
	var envelope struct {
		Result json.RawMessage {Q}json:"result"{Q}
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, err
	}
	return envelope.Result, nil
}

`

// goCapability 渲染一个 capability 的输入类型与调用方法。
func goCapability(builder *strings.Builder, capability capability.CapabilitySpec, model *TypeModel, packageID string) {
	for _, namedModel := range collectNamed(model) {
		switch namedModel.Kind {
		case KindEnum:
			goEnumType(builder, namedModel)
		case KindObject:
			goStructType(builder, namedModel)
		}
	}
	method := goMethodName(capability.ID, packageID)
	fmt.Fprintf(builder, "// %s 调用 %s。\n", method, capability.ID)
	// 根 schema 可能是标量（具名类型的 Name 才非空），故经 goFieldType 映射。
	fmt.Fprintf(builder, "func (c *Client) %s(ctx context.Context, input %s, options ...CallOption) (json.RawMessage, error) {\n", method, goFieldType(model, true))
	fmt.Fprintf(builder, "\treturn c.invoke(ctx, %q, input, options...)\n}\n\n", capability.ID)
}

// goEnumType 渲染 enum 具名类型与常量（enum 基类型只有 string，见 schema.go）。
func goEnumType(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "type %s string\n\nconst (\n", model.Name)
	for _, value := range model.Values {
		fmt.Fprintf(builder, "\t%s %s = %q\n", model.Name+strcase.ToCamel(value), model.Name, value)
	}
	builder.WriteString(")\n\n")
}

// goStructType 渲染 object 具名 struct：字段名转 CamelCase，可选字段带 omitempty。
func goStructType(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "type %s struct {\n", model.Name)
	for _, field := range model.Fields {
		tag := `json:"` + field.Name
		if !field.Required {
			tag += ",omitempty"
		}
		tag += `"`
		fmt.Fprintf(builder, "\t%s %s `%s`\n", goFieldName(field.Name), goFieldType(field.Type, field.Required), tag)
	}
	builder.WriteString("}\n\n")
}

// goFieldType 映射字段类型：非必填标量与对象用指针（区分未提供与零值），
// 数组用值（nil slice 经 omitempty 省略）。
func goFieldType(model *TypeModel, required bool) string {
	base := ""
	switch model.Kind {
	case KindString:
		base = "string"
	case KindInteger:
		base = "int64"
	case KindNumber:
		base = "float64"
	case KindBoolean:
		base = "bool"
	case KindDateTime:
		base = "time.Time"
	case KindEnum, KindObject:
		base = model.Name
	case KindArray:
		base = "[]" + goFieldType(model.Elem, true)
		if !required {
			return "*" + base
		}
		return base
	}
	if !required {
		return "*" + base
	}
	return base
}
