package sdkgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
)

// emitGo 渲染 Go SDK：一个 client.go，包含传输层与每个 capability 的类型化方法。
func emitGo(packageID string, capabilities []Capability, models map[string]*TypeModel) []Generated {
	var builder strings.Builder
	fmt.Fprintf(&builder, "// Code generated by ailuo sdkgen. DO NOT EDIT.\n//\n// Source: %s\npackage %s\n\n", packageID, packageName(packageID))
	builder.WriteString(goHeader)
	builder.WriteString(strings.ReplaceAll(goClient, "{Q}", "`"))
	for _, capability := range capabilities {
		goCapability(&builder, capability, models[capability.ID], packageID)
	}
	return []Generated{{Path: packageName(packageID) + "/client.go", Code: []byte(builder.String())}}
}

const goHeader = `import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

`

const goClient = `// Client 调用内核 capability，经 invoke 端点（POST /api/v1/capabilities/{id}/invoke）。
type Client struct {
	baseURL string
	http    *http.Client
}

// NewClient 构造消费方客户端。
func NewClient(baseURL string) *Client {
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), http: &http.Client{Timeout: 30 * time.Second}}
}

// invoke 是最小传输信封：{"input": <payload>} → {"result": <value>}。
func (c *Client) invoke(ctx context.Context, capabilityID string, input any) (json.RawMessage, error) {
	payload, err := json.Marshal(struct {
		Input any {Q}json:"input"{Q}
	}{Input: input})
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost,
		c.baseURL+"/api/v1/capabilities/"+url.PathEscape(capabilityID)+"/invoke", bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	request.Header.Set("Content-Type", "application/json")
	response, err := c.http.Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	body, err := io.ReadAll(io.LimitReader(response.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if response.StatusCode != http.StatusOK {
		var apiError struct {
			Code    string {Q}json:"code"{Q}
			Message string {Q}json:"message"{Q}
		}
		_ = json.Unmarshal(body, &apiError)
		return nil, fmt.Errorf("ailuo invoke %s: %s: %s", capabilityID, response.Status, apiError.Message)
	}
	var envelope struct {
		Result json.RawMessage {Q}json:"result"{Q}
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, err
	}
	return envelope.Result, nil
}

`

// goCapability 渲染一个 capability 的输入类型与调用方法。
func goCapability(builder *strings.Builder, capability Capability, model *TypeModel, packageID string) {
	for _, namedModel := range collectNamed(model) {
		switch namedModel.Kind {
		case KindEnum:
			goEnumType(builder, namedModel)
		case KindObject:
			goStructType(builder, namedModel)
		}
	}
	method := goMethodName(capability.ID, packageID)
	fmt.Fprintf(builder, "// %s 调用 %s。\n", method, capability.ID)
	fmt.Fprintf(builder, "func (c *Client) %s(ctx context.Context, input %s) (json.RawMessage, error) {\n", method, model.Name)
	fmt.Fprintf(builder, "\treturn c.invoke(ctx, %q, input)\n}\n\n", capability.ID)
}

// goEnumType 渲染 enum 具名类型与常量。
func goEnumType(builder *strings.Builder, model *TypeModel) {
	base := "string"
	if model.Base == KindInteger {
		base = "int64"
	}
	fmt.Fprintf(builder, "type %s %s\n\nconst (\n", model.Name, base)
	for _, value := range model.Values {
		constant := model.Name + strcase.ToCamel(value)
		if model.Base == KindInteger {
			fmt.Fprintf(builder, "\t%s %s = %s\n", constant, model.Name, value)
		} else {
			fmt.Fprintf(builder, "\t%s %s = %q\n", constant, model.Name, value)
		}
	}
	builder.WriteString(")\n\n")
}

// goStructType 渲染 object 具名 struct：必填字段在前，字段名转 CamelCase。
func goStructType(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "type %s struct {\n", model.Name)
	fields := append([]Field(nil), model.Fields...)
	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Required && !fields[j].Required
	})
	for _, field := range fields {
		tag := `json:"` + field.Name
		if !field.Required {
			tag += ",omitempty"
		}
		tag += `"`
		fmt.Fprintf(builder, "\t%s %s `%s`\n", goFieldName(field.Name), goFieldType(field.Type, field.Required), tag)
	}
	builder.WriteString("}\n\n")
}

// goFieldType 映射字段类型：非必填标量与对象用指针（区分未提供与零值），
// 数组用值（nil slice 经 omitempty 省略）。
func goFieldType(model *TypeModel, required bool) string {
	base := ""
	switch model.Kind {
	case KindString:
		base = "string"
	case KindInteger:
		base = "int64"
	case KindNumber:
		base = "float64"
	case KindBoolean:
		base = "bool"
	case KindDateTime:
		base = "time.Time"
	case KindEnum, KindObject:
		base = model.Name
	case KindArray:
		return "[]" + goFieldType(model.Elem, true)
	}
	if !required {
		return "*" + base
	}
	return base
}
