package sdkgen

import (
	"fmt"
	"strings"
)

// emitTypeScript 渲染 TypeScript SDK：client.ts，包含传输层与每个 capability
// 的类型化方法（async/await + fetch 标准 API，仅浏览器/Deno 运行时）。
func emitTypeScript(packageID string, capabilities []Capability, models map[string]*TypeModel) []Generated {
	var builder strings.Builder
	pkgName := packageName(packageID)
	fmt.Fprintf(&builder, "// Code generated by ailuo sdkgen. DO NOT EDIT.\n//\n// Source: %s\n\n", packageID)
	// 所有类型定义（interface / union type），置于 class 之前。
	for _, capability := range capabilities {
		for _, namedModel := range collectNamed(models[capability.ID]) {
			switch namedModel.Kind {
			case KindEnum:
				tsUnionType(&builder, namedModel)
			case KindObject:
				tsInterface(&builder, namedModel)
			}
		}
	}
	// Client class：构造 + invoke 传输层 + 每 capability 方法。
	fmt.Fprintf(&builder, "export class %sClient {\n", strings.Title(pkgName))
	builder.WriteString(strings.ReplaceAll(tsClientTemplate, "{Q}", "`"))
	for _, capability := range capabilities {
		tsCapability(&builder, capability, models[capability.ID], packageID)
	}
	builder.WriteString("}\n")
	return []Generated{{Path: pkgName + "/client.ts", Code: []byte(builder.String())}}
}

// tsCapability 渲染一个 capability 的类型化方法（与 goCapability/pythonCapability 对称）。
func tsCapability(builder *strings.Builder, capability Capability, model *TypeModel, packageID string) {
	name := tsMethodName(capability.ID, packageID)
	fmt.Fprintf(builder, "  %s(input: %s): Promise<unknown> {\n", name, model.Name)
	fmt.Fprintf(builder, "    return this.invoke(%q, input);\n", capability.ID)
	builder.WriteString("  }\n\n")
}

// tsClientTemplate 是 Client 构造与 invoke 传输层模板；{Q} 渲染时替换为反引号
// （TypeScript 模板字符串语法，Go 反引号字符串无法直接承载）。
const tsClientTemplate = `  private baseUrl: string;
  constructor(baseUrl: string) {
    this.baseUrl = baseUrl.replace(/\/+$/, "");
  }

  private async invoke(capabilityId: string, input: unknown): Promise<unknown> {
    const response = await fetch({Q}${this.baseUrl}/api/v1/capabilities/${capabilityId}/invoke{Q}, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ input }),
    });
    if (!response.ok) {
      let message = "";
      try { const body = await response.json() as { message?: string }; message = body.message ?? ""; } catch {}
      throw new Error({Q}ailuo invoke ${capabilityId}: ${response.status}: ${message}{Q});
    }
    const envelope = (await response.json()) as { result: unknown };
    return envelope.result;
  }

`

// tsInterface 渲染 object 为 interface（字段用 JSON key 名，可选加 ?）。
func tsInterface(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "export interface %s {\n", model.Name)
	for _, field := range model.Fields {
		opt := ""
		if !field.Required {
			opt = "?"
		}
		fmt.Fprintf(builder, "  %s%s: %s;\n", field.Name, opt, tsFieldType(field.Type))
	}
	builder.WriteString("}\n\n")
}

// tsUnionType 渲染 enum 为 union type。
func tsUnionType(builder *strings.Builder, model *TypeModel) {
	values := make([]string, 0, len(model.Values))
	for _, value := range model.Values {
		values = append(values, fmt.Sprintf("%q", value))
	}
	fmt.Fprintf(builder, "export type %s = %s;\n\n", model.Name, strings.Join(values, " | "))
}

// tsFieldType 映射字段类型注解。TS 可选性由 interface 属性级 ? 表达
// （见 tsInterface），与 Go 指针、Python Optional 同语义但位置在属性声明，
// 故本函数无需 required 参数。
func tsFieldType(model *TypeModel) string {
	switch model.Kind {
	case KindString:
		return "string"
	case KindInteger, KindNumber:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindDateTime:
		return "Date"
	case KindEnum, KindObject:
		return model.Name
	case KindArray:
		return tsFieldType(model.Elem) + "[]"
	default:
		return "unknown"
	}
}
