package sdkgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/projectluojia/AI-Luo-Man-ga/pkg/capability"
)

// emitPython 渲染 Python SDK：client.py（实现）+ __init__.py（重新导出公共
// 符号），使消费方 `from campus import Client` 可用（namespace package 无法
// 从子模块顶层导入）。
func emitPython(packageID string, capabilities []capability.CapabilitySpec, models map[string]*TypeModel) []Generated {
	pkgName := packageName(packageID)
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Code generated by ailuo sdkgen. DO NOT EDIT.\n#\n# Source: %s\n", packageID)
	builder.WriteString(pythonHeader(capabilities, models))
	builder.WriteString(pythonClient)
	for _, capability := range capabilities {
		pythonCapability(&builder, capability, models[capability.ID], packageID)
	}
	return []Generated{
		{Path: pkgName + "/client.py", Code: []byte(builder.String())},
		{Path: pkgName + "/__init__.py", Code: []byte(pythonInit(packageID, capabilities, models))},
	}
}

// pythonInit 渲染 __init__.py：重新导出 Client 与所有类型化符号。方法名按完整
// packageID 去前缀派生（与 pythonCapability 一致）：pkgName 只是 ID 首段
// （campus.bus → campus），用它派生会导出不存在的符号 → import 即 ImportError。
func pythonInit(packageID string, capabilities []capability.CapabilitySpec, models map[string]*TypeModel) []byte {
	var builder strings.Builder
	builder.WriteString("# Code generated by ailuo sdkgen. DO NOT EDIT.\nfrom .client import CallOptions, Client, InvokeError\n")
	seen := make(map[string]struct{})
	for _, capability := range capabilities {
		fmt.Fprintf(&builder, "from .client import %s\n", pythonMethodName(capability.ID, packageID))
		for _, namedModel := range collectNamed(models[capability.ID]) {
			if _, exists := seen[namedModel.Name]; exists {
				continue
			}
			seen[namedModel.Name] = struct{}{}
			fmt.Fprintf(&builder, "from .client import %s\n", namedModel.Name)
		}
	}
	return []byte(builder.String())
}

// pythonHeader 渲染固定导入与按需的 enum 导入。
func pythonHeader(capabilities []capability.CapabilitySpec, models map[string]*TypeModel) string {
	imports := "from dataclasses import asdict, dataclass\nfrom datetime import datetime\nimport json\nfrom typing import Any, Callable, Mapping, Optional\nfrom urllib import error, request\n"
	for _, capability := range capabilities {
		for _, namedModel := range collectNamed(models[capability.ID]) {
			if namedModel.Kind == KindEnum {
				return imports + "from enum import Enum\n\n"
			}
		}
	}
	return imports + "\n"
}

const pythonClient = `@dataclass
class CallOptions:
    """一次 Capability 调用的治理字段。"""

    idempotency_key: Optional[str] = None
    confirmation_id: Optional[str] = None


class InvokeError(RuntimeError):
    """invoke 端点返回的稳定结构化错误。"""

    def __init__(self, status: int, code: str, message: str, retryable: bool = False) -> None:
        super().__init__(f"ailuo invoke failed: HTTP {status} {code}: {message}")
        self.status = status
        self.code = code
        self.message = message
        self.retryable = retryable


class Client:
    """内核 capability 消费方客户端。"""

    def __init__(
        self,
        base_url: str,
        *,
        timeout: float = 30.0,
        headers: Optional[Mapping[str, str]] = None,
        header_provider: Optional[Callable[[str], Mapping[str, str]]] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout
        self._headers = dict(headers or {})
        self._header_provider = header_provider

    def _invoke(self, capability_id: str, payload: Any, options: Optional[CallOptions] = None) -> Any:
        body = json.dumps(
            {"input": payload},
            default=_json_default,
        ).encode("utf-8")
        headers = {"Content-Type": "application/json", **self._headers}
        if self._header_provider is not None:
            headers.update(self._header_provider(capability_id))
        if options is not None and options.idempotency_key is not None:
            headers["Idempotency-Key"] = options.idempotency_key
        if options is not None and options.confirmation_id is not None:
            headers["X-Confirmation-ID"] = options.confirmation_id
        req = request.Request(
            f"{self._base_url}/api/v1/capabilities/{capability_id}/invoke",
            data=body,
            headers=headers,
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=self._timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))["result"]
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            try:
                response_body = json.loads(detail)
            except ValueError:
                response_body = None
            if (
                not isinstance(response_body, dict)
                or not isinstance(response_body.get("code"), str)
                or not isinstance(response_body.get("message"), str)
            ):
                raise InvokeError(exc.code, "invalid_response", "服务端错误响应格式无效") from exc
            code = response_body["code"]
            message = response_body["message"]
            retryable = response_body.get("retryable") is True
            raise InvokeError(exc.code, code, message, retryable) from exc


def _json_default(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.astimezone().isoformat()
    if hasattr(value, "__dataclass_fields__"):
        return _drop_none(asdict(value))
    raise TypeError(f"cannot serialize {type(value).__name__}")


def _drop_none(value: Any) -> Any:
    """递归剔除 None：asdict 会把嵌套 dataclass 一并转成 dict，只在顶层过滤
    会把嵌套的未提供字段当显式 null 发给内核（严格 schema 会拒收）。"""
    if isinstance(value, dict):
        return {k: _drop_none(v) for k, v in value.items() if v is not None}
    if isinstance(value, list):
        return [_drop_none(v) for v in value]
    return value


`

// pythonCapability 渲染一个 capability 的输入 dataclass 与调用函数。
func pythonCapability(builder *strings.Builder, capability capability.CapabilitySpec, model *TypeModel, packageID string) {
	for _, namedModel := range collectNamed(model) {
		switch namedModel.Kind {
		case KindEnum:
			pythonEnumType(builder, namedModel)
		case KindObject:
			pythonDataclass(builder, namedModel)
		}
	}
	name := pythonMethodName(capability.ID, packageID)
	// 根 schema 可能是标量（具名类型的 Name 才非空），故经 pythonFieldType 映射。
	fmt.Fprintf(builder, "def %s(client: Client, input: %s, options: Optional[CallOptions] = None) -> Any:\n", name, pythonFieldType(model, true))
	fmt.Fprintf(builder, "    \"\"\"调用 %s。\"\"\"\n", capability.ID)
	fmt.Fprintf(builder, "    return client._invoke(%q, input, options)\n\n\n", capability.ID)
}

// pythonEnumType 渲染 str Enum（enum 基类型只有 string，见 schema.go）。
func pythonEnumType(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "class %s(str, Enum):\n", model.Name)
	for _, value := range model.Values {
		fmt.Fprintf(builder, "    %s = %q\n", strcase.ToCamel(value), value)
	}
	builder.WriteString("\n\n")
}

// pythonDataclass 渲染 object dataclass：必填字段在前（无默认值）。
func pythonDataclass(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "@dataclass\nclass %s:\n", model.Name)
	fields := append([]Field(nil), model.Fields...)
	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Required && !fields[j].Required
	})
	for _, field := range fields {
		if field.Required {
			fmt.Fprintf(builder, "    %s: %s\n", field.Name, pythonFieldType(field.Type, true))
		} else {
			fmt.Fprintf(builder, "    %s: %s = None\n", field.Name, pythonFieldType(field.Type, false))
		}
	}
	builder.WriteString("\n\n")
}

// pythonFieldType 映射字段类型注解：非必填包 Optional（与 Go 指针、TS 可选同语义）。
func pythonFieldType(model *TypeModel, required bool) string {
	base := ""
	switch model.Kind {
	case KindString:
		base = "str"
	case KindInteger:
		base = "int"
	case KindNumber:
		base = "float"
	case KindBoolean:
		base = "bool"
	case KindDateTime:
		base = "datetime"
	case KindEnum, KindObject:
		base = model.Name
	case KindArray:
		return "list[" + pythonFieldType(model.Elem, true) + "]"
	}
	if !required {
		return "Optional[" + base + "]"
	}
	return base
}
