package sdkgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
)

// emitGo 渲染 Go SDK：一个 client.go，包含传输层与每个 capability 的类型化方法。
// emitter 是纯渲染（错误只在契约/schema 编译阶段产生），不返回 error。
func emitGo(packageID string, capabilities []Capability, models map[string]*TypeModel) []Generated {
	var builder strings.Builder
	fmt.Fprintf(&builder, "// Code generated by ailuo sdkgen. DO NOT EDIT.\n//\n// Source: %s\npackage %s\n\n", packageID, packageName(packageID))
	builder.WriteString(goHeader)
	builder.WriteString(strings.ReplaceAll(goClient, "{Q}", "`"))
	for _, capability := range capabilities {
		goCapability(&builder, capability, models[capability.ID], packageID)
	}
	return []Generated{{Path: packageName(packageID) + "/client.go", Code: []byte(builder.String())}}
}

const goHeader = `import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

`

// goClient 是最小传输层模板；{Q} 在渲染时替换为反引号（struct tag 语法）。
const goClient = `// Client 调用内核 capability，经 invoke 端点（POST /api/v1/capabilities/{id}/invoke）。
type Client struct {
	baseURL string
	http    *http.Client
}

// NewClient 构造消费方客户端。
func NewClient(baseURL string) *Client {
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), http: &http.Client{Timeout: 30 * time.Second}}
}

// invoke 是最小传输信封：{"input": <payload>} → {"result": <value>}。
func (c *Client) invoke(ctx context.Context, capabilityID string, input any) (json.RawMessage, error) {
	payload, err := json.Marshal(struct {
		Input any {Q}json:"input"{Q}
	}{Input: input})
	if err != nil {
		return nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost,
		c.baseURL+"/api/v1/capabilities/"+url.PathEscape(capabilityID)+"/invoke", bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	request.Header.Set("Content-Type", "application/json")
	response, err := c.http.Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	body, err := io.ReadAll(io.LimitReader(response.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if response.StatusCode != http.StatusOK {
		var apiError struct {
			Code    string {Q}json:"code"{Q}
			Message string {Q}json:"message"{Q}
		}
		_ = json.Unmarshal(body, &apiError)
		return nil, fmt.Errorf("ailuo invoke %s: %s: %s", capabilityID, response.Status, apiError.Message)
	}
	var envelope struct {
		Result json.RawMessage {Q}json:"result"{Q}
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, err
	}
	return envelope.Result, nil
}

`

// goCapability 渲染一个 capability 的输入类型与调用方法。
func goCapability(builder *strings.Builder, capability Capability, model *TypeModel, packageID string) {
	named := collectNamed(model)
	for _, namedModel := range named {
		switch namedModel.Kind {
		case KindEnum:
			goEnumType(builder, namedModel)
		case KindObject:
			goStructType(builder, namedModel)
		}
	}
	method := goMethodName(capability.ID, packageID)
	fmt.Fprintf(builder, "// %s 调用 %s。\n", method, capability.ID)
	fmt.Fprintf(builder, "func (c *Client) %s(ctx context.Context, input %s) (json.RawMessage, error) {\n", method, model.Name)
	fmt.Fprintf(builder, "\treturn c.invoke(ctx, %q, input)\n}\n\n", capability.ID)
}

// collectNamed 深度优先收集具名类型（object/enum），按出现顺序去重。
func collectNamed(model *TypeModel) []*TypeModel {
	var ordered []*TypeModel
	seen := make(map[string]struct{})
	var visit func(*TypeModel)
	visit = func(current *TypeModel) {
		if current == nil {
			return
		}
		if current.Kind == KindObject || current.Kind == KindEnum {
			if _, exists := seen[current.Name]; exists {
				return
			}
			seen[current.Name] = struct{}{}
			ordered = append(ordered, current)
			if current.Kind == KindObject {
				for _, field := range current.Fields {
					visit(field.Type)
				}
			}
			return
		}
		if current.Kind == KindArray {
			visit(current.Elem)
		}
	}
	visit(model)
	return ordered
}

// goEnumType 渲染 enum 具名类型与常量。
func goEnumType(builder *strings.Builder, model *TypeModel) {
	base := "string"
	if model.Base == KindInteger {
		base = "int64"
	}
	fmt.Fprintf(builder, "type %s %s\n\nconst (\n", model.Name, base)
	for _, value := range model.Values {
		constant := model.Name + strcase.ToCamel(value)
		if model.Base == KindInteger {
			fmt.Fprintf(builder, "\t%s %s = %s\n", constant, model.Name, value)
		} else {
			fmt.Fprintf(builder, "\t%s %s = %q\n", constant, model.Name, value)
		}
	}
	builder.WriteString(")\n\n")
}

// goStructType 渲染 object 具名 struct：必填字段在前，字段名转 CamelCase。
func goStructType(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "type %s struct {\n", model.Name)
	fields := append([]Field(nil), model.Fields...)
	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Required && !fields[j].Required
	})
	for _, field := range fields {
		tag := `json:"` + field.Name
		if !field.Required {
			tag += ",omitempty"
		}
		tag += `"`
		fmt.Fprintf(builder, "\t%s %s `%s`\n", goFieldName(field.Name), goFieldType(field.Type, field.Required), tag)
	}
	builder.WriteString("}\n\n")
}

// goFieldType 映射字段类型：非必填标量与对象用指针（区分未提供与零值），
// 数组用值（nil slice 经 omitempty 省略）。
func goFieldType(model *TypeModel, required bool) string {
	base := ""
	switch model.Kind {
	case KindString:
		base = "string"
	case KindInteger:
		base = "int64"
	case KindNumber:
		base = "float64"
	case KindBoolean:
		base = "bool"
	case KindDateTime:
		base = "time.Time"
	case KindEnum, KindObject:
		base = model.Name
	case KindArray:
		return "[]" + goFieldType(model.Elem, true)
	}
	if !required {
		return "*" + base
	}
	return base
}

// emitPython 渲染 Python SDK：一个 client.py，包含传输层与每个 capability 的类型化函数。
func emitPython(packageID string, capabilities []Capability, models map[string]*TypeModel) []Generated {
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Code generated by ailuo sdkgen. DO NOT EDIT.\n#\n# Source: %s\n", packageID)
	builder.WriteString(pythonHeader(capabilities, models))
	builder.WriteString(pythonClient)
	for _, capability := range capabilities {
		pythonCapability(&builder, capability, models[capability.ID], packageID)
	}
	return []Generated{{Path: packageName(packageID) + "/client.py", Code: []byte(builder.String())}}
}

// pythonHeader 渲染固定导入与按需的 enum/dataclass 导入。
func pythonHeader(capabilities []Capability, models map[string]*TypeModel) string {
	needsEnum := false
	for _, capability := range capabilities {
		if hasKind(models[capability.ID], KindEnum) {
			needsEnum = true
			break
		}
	}
	imports := "from dataclasses import asdict, dataclass\nfrom datetime import datetime\nimport json\nfrom typing import Any, Optional\nfrom urllib import error, request\n"
	if needsEnum {
		imports += "from enum import Enum\n"
	}
	return imports + "\n"
}

// hasKind 判断类型树中是否存在指定 kind。
func hasKind(model *TypeModel, kind TypeKind) bool {
	if model == nil {
		return false
	}
	if model.Kind == kind {
		return true
	}
	if model.Kind == KindArray {
		return hasKind(model.Elem, kind)
	}
	if model.Kind == KindObject {
		for _, field := range model.Fields {
			if hasKind(field.Type, kind) {
				return true
			}
		}
	}
	return false
}

const pythonClient = `class Client:
    """内核 capability 消费方客户端。"""

    def __init__(self, base_url: str, *, timeout: float = 30.0) -> None:
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout

    def _invoke(self, capability_id: str, payload: Any) -> Any:
        body = json.dumps(
            {"input": payload},
            default=_json_default,
        ).encode("utf-8")
        req = request.Request(
            f"{self._base_url}/api/v1/capabilities/{capability_id}/invoke",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=self._timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))["result"]
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"ailuo invoke {capability_id}: HTTP {exc.code}: {detail}") from exc


def _json_default(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat()
    if hasattr(value, "__dataclass_fields__"):
        return asdict(value)
    raise TypeError(f"cannot serialize {type(value).__name__}")


`

// pythonCapability 渲染一个 capability 的输入 dataclass 与调用函数。
func pythonCapability(builder *strings.Builder, capability Capability, model *TypeModel, packageID string) {
	for _, namedModel := range collectNamed(model) {
		switch namedModel.Kind {
		case KindEnum:
			pythonEnumType(builder, namedModel)
		case KindObject:
			pythonDataclass(builder, namedModel)
		}
	}
	name := pythonMethodName(capability.ID, packageID)
	fmt.Fprintf(builder, "def %s(client: Client, input: %s) -> Any:\n", name, model.Name)
	fmt.Fprintf(builder, "    \"\"\"调用 %s。\"\"\"\n", capability.ID)
	fmt.Fprintf(builder, "    return client._invoke(%q, input)\n\n\n", capability.ID)
}

// pythonEnumType 渲染 str/int Enum。
func pythonEnumType(builder *strings.Builder, model *TypeModel) {
	base := "str"
	if model.Base == KindInteger {
		base = "int"
	}
	fmt.Fprintf(builder, "class %s(%s, Enum):\n", model.Name, base)
	for _, value := range model.Values {
		member := strcase.ToCamel(value)
		if model.Base == KindInteger {
			fmt.Fprintf(builder, "    %s = %s\n", member, value)
		} else {
			fmt.Fprintf(builder, "    %s = %q\n", member, value)
		}
	}
	builder.WriteString("\n\n")
}

// pythonDataclass 渲染 object dataclass：必填字段在前（无默认值）。
func pythonDataclass(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "@dataclass\nclass %s:\n", model.Name)
	fields := append([]Field(nil), model.Fields...)
	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Required && !fields[j].Required
	})
	for _, field := range fields {
		annotation := pythonFieldType(field.Type)
		if !field.Required {
			annotation = "Optional[" + annotation + "]"
			fmt.Fprintf(builder, "    %s: %s = None\n", field.Name, annotation)
		} else {
			fmt.Fprintf(builder, "    %s: %s\n", field.Name, annotation)
		}
	}
	builder.WriteString("\n\n")
}

// pythonFieldType 映射字段类型注解。
func pythonFieldType(model *TypeModel) string {
	switch model.Kind {
	case KindString:
		return "str"
	case KindInteger:
		return "int"
	case KindNumber:
		return "float"
	case KindBoolean:
		return "bool"
	case KindDateTime:
		return "datetime"
	case KindEnum, KindObject:
		return model.Name
	case KindArray:
		return "list[" + pythonFieldType(model.Elem) + "]"
	default:
		return "Any"
	}
}
