package sdkgen

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerateTypeScriptShape(t *testing.T) {
	code := generateForTest(t, LanguageTypeScript)
	required := []string{
		"// Code generated by ailuo sdkgen. DO NOT EDIT.",
		"export interface BusStopsSearchInput {",
		"  query: string;",
		"  limit?: number;",
		"export interface BusJourneysSearchInput {",
		"  origin_stop_id: string;",
		"  destination_stop_id: string;",
		"  depart_after?: Date;",
		"export class CampusClient {",
		"private async invoke(capabilityId: string, input: unknown): Promise<unknown> {",
		"/api/v1/capabilities/${capabilityId}/invoke",
		"busStopsSearch(input: BusStopsSearchInput): Promise<unknown> {",
		`return this.invoke("campus.bus.stops.search", input);`,
		"busJourneysSearch(input: BusJourneysSearchInput): Promise<unknown> {",
	}
	for _, want := range required {
		if !strings.Contains(code, want) {
			t.Errorf("TypeScript 生成代码缺少 %q\n---\n%s", want, code)
		}
	}
}

func TestGenerateTypeScriptCompiles(t *testing.T) {
	if _, err := exec.LookPath("npx"); err != nil {
		t.Skip("npx 不可用，跳过 tsc 编译验证")
	}
	dir := t.TempDir()
	files, err := Generate(json.RawMessage(campusExtensions), Options{Language: LanguageTypeScript, PackageID: "campus"})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		path := filepath.Join(dir, f.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, f.Code, 0644); err != nil {
			t.Fatal(err)
		}
	}
	// 最小 tsconfig：strict + DOM（fetch/Response 类型）。
	tsconfig := `{"compilerOptions":{"strict":true,"target":"ES2020","module":"ESNext","lib":["ES2020","DOM"],"noEmit":true},"include":["campus/**/*.ts"]}`
	if err := os.WriteFile(filepath.Join(dir, "tsconfig.json"), []byte(tsconfig), 0644); err != nil {
		t.Fatal(err)
	}
	// npx 首次运行需下载 typescript：绑定超时上下文，卡在网络时子进程被杀。
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	command := exec.CommandContext(ctx, "npx", "--yes", "--package", "typescript", "tsc", "-p", ".")
	command.Dir = dir
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("tsc 编译失败: %v\n%s", err, output)
	}
}
