package sdkgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
)

// emitPython 渲染 Python SDK：client.py（实现）+ __init__.py（重新导出公共
// 符号），使消费方 `from campus import Client` 可用（namespace package 无法
// 从子模块顶层导入）。
func emitPython(packageID string, capabilities []Capability, models map[string]*TypeModel) []Generated {
	pkgName := packageName(packageID)
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Code generated by ailuo sdkgen. DO NOT EDIT.\n#\n# Source: %s\n", packageID)
	builder.WriteString(pythonHeader(capabilities, models))
	builder.WriteString(pythonClient)
	for _, capability := range capabilities {
		pythonCapability(&builder, capability, models[capability.ID], packageID)
	}
	return []Generated{
		{Path: pkgName + "/client.py", Code: []byte(builder.String())},
		{Path: pkgName + "/__init__.py", Code: []byte(pythonInit(pkgName, capabilities, models))},
	}
}

// pythonInit 渲染 __init__.py：重新导出 Client 与所有类型化符号。
func pythonInit(pkgName string, capabilities []Capability, models map[string]*TypeModel) []byte {
	var builder strings.Builder
	builder.WriteString("# Code generated by ailuo sdkgen. DO NOT EDIT.\n")
	fmt.Fprintf(&builder, "from .client import Client\n")
	seen := make(map[string]struct{})
	for _, capability := range capabilities {
		fmt.Fprintf(&builder, "from .client import %s\n", pythonMethodName(capability.ID, pkgName))
		for _, namedModel := range collectNamed(models[capability.ID]) {
			if _, exists := seen[namedModel.Name]; exists {
				continue
			}
			seen[namedModel.Name] = struct{}{}
			fmt.Fprintf(&builder, "from .client import %s\n", namedModel.Name)
		}
	}
	return []byte(builder.String())
}

// pythonHeader 渲染固定导入与按需的 enum 导入。
func pythonHeader(capabilities []Capability, models map[string]*TypeModel) string {
	imports := "from dataclasses import asdict, dataclass\nfrom datetime import datetime\nimport json\nfrom typing import Any, Optional\nfrom urllib import error, request\n"
	for _, capability := range capabilities {
		if hasKind(models[capability.ID], KindEnum) {
			imports += "from enum import Enum\n"
			break
		}
	}
	return imports + "\n"
}

const pythonClient = `class Client:
    """内核 capability 消费方客户端。"""

    def __init__(self, base_url: str, *, timeout: float = 30.0) -> None:
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout

    def _invoke(self, capability_id: str, payload: Any) -> Any:
        body = json.dumps(
            {"input": payload},
            default=_json_default,
        ).encode("utf-8")
        req = request.Request(
            f"{self._base_url}/api/v1/capabilities/{capability_id}/invoke",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=self._timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))["result"]
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"ailuo invoke {capability_id}: HTTP {exc.code}: {detail}") from exc


def _json_default(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.astimezone().isoformat()
    if hasattr(value, "__dataclass_fields__"):
        return {k: v for k, v in asdict(value).items() if v is not None}
    raise TypeError(f"cannot serialize {type(value).__name__}")


`

// pythonCapability 渲染一个 capability 的输入 dataclass 与调用函数。
func pythonCapability(builder *strings.Builder, capability Capability, model *TypeModel, packageID string) {
	for _, namedModel := range collectNamed(model) {
		switch namedModel.Kind {
		case KindEnum:
			pythonEnumType(builder, namedModel)
		case KindObject:
			pythonDataclass(builder, namedModel)
		}
	}
	name := pythonMethodName(capability.ID, packageID)
	fmt.Fprintf(builder, "def %s(client: Client, input: %s) -> Any:\n", name, model.Name)
	fmt.Fprintf(builder, "    \"\"\"调用 %s。\"\"\"\n", capability.ID)
	fmt.Fprintf(builder, "    return client._invoke(%q, input)\n\n\n", capability.ID)
}

// pythonEnumType 渲染 str/int Enum。
func pythonEnumType(builder *strings.Builder, model *TypeModel) {
	base := "str"
	if model.Base == KindInteger {
		base = "int"
	}
	fmt.Fprintf(builder, "class %s(%s, Enum):\n", model.Name, base)
	for _, value := range model.Values {
		member := strcase.ToCamel(value)
		if model.Base == KindInteger {
			fmt.Fprintf(builder, "    %s = %s\n", member, value)
		} else {
			fmt.Fprintf(builder, "    %s = %q\n", member, value)
		}
	}
	builder.WriteString("\n\n")
}

// pythonDataclass 渲染 object dataclass：必填字段在前（无默认值）。
func pythonDataclass(builder *strings.Builder, model *TypeModel) {
	fmt.Fprintf(builder, "@dataclass\nclass %s:\n", model.Name)
	fields := append([]Field(nil), model.Fields...)
	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Required && !fields[j].Required
	})
	for _, field := range fields {
		if field.Required {
			fmt.Fprintf(builder, "    %s: %s\n", field.Name, pythonFieldType(field.Type, true))
		} else {
			fmt.Fprintf(builder, "    %s: %s = None\n", field.Name, pythonFieldType(field.Type, false))
		}
	}
	builder.WriteString("\n\n")
}

// pythonFieldType 映射字段类型注解：非必填包 Optional（与 Go 指针、TS 可选同语义）。
func pythonFieldType(model *TypeModel, required bool) string {
	base := ""
	switch model.Kind {
	case KindString:
		base = "str"
	case KindInteger:
		base = "int"
	case KindNumber:
		base = "float"
	case KindBoolean:
		base = "bool"
	case KindDateTime:
		base = "datetime"
	case KindEnum, KindObject:
		base = model.Name
	case KindArray:
		return "list[" + pythonFieldType(model.Elem, true) + "]"
	}
	if !required {
		return "Optional[" + base + "]"
	}
	return base
}
