package sdkgen

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// campusExtensions 是独立包仓库 ailuo-packages/campus-bus 三个 capability 的
// 契约快照（packagefmt 输出的 extensions 段形状），用于驱动生成测试。
// sdkgen 是中立包（不依赖内核 internal），故以静态快照而非实时契约驱动。
const campusExtensions = `{
	"tools": [],
	"service": {"id": "campus"},
	"capabilities": [
		{
			"id": "campus.bus.stops.search",
			"version": "1.0.0",
			"name": "查询校巴站点",
			"description": "Search authoritative campus bus stops by name or alias.",
			"input_schema_json": "{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\",\"minLength\":1},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":50}},\"required\":[\"query\"],\"additionalProperties\":false}"
		},
		{
			"id": "campus.bus.routes.list",
			"version": "1.0.0",
			"name": "列出校巴线路",
			"description": "List authoritative campus bus routes.",
			"input_schema_json": "{\"type\":\"object\",\"properties\":{\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":50}},\"additionalProperties\":false}"
		},
		{
			"id": "campus.bus.journeys.search",
			"version": "1.0.0",
			"name": "查询校巴行程",
			"description": "Search authoritative campus bus journeys by stops and departure time.",
			"input_schema_json": "{\"type\":\"object\",\"properties\":{\"origin_stop_id\":{\"type\":\"string\",\"minLength\":1},\"destination_stop_id\":{\"type\":\"string\",\"minLength\":1},\"depart_after\":{\"type\":\"string\",\"format\":\"date-time\"},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":50}},\"required\":[\"origin_stop_id\",\"destination_stop_id\"],\"additionalProperties\":false}"
		}
	]
}`

func generateForTest(t *testing.T, language Language) string {
	t.Helper()
	files, err := Generate(json.RawMessage(campusExtensions), Options{Language: language, PackageID: "campus"})
	if err != nil {
		t.Fatalf("Generate(%s): %v", language, err)
	}
	if len(files) == 0 {
		t.Fatalf("Generate(%s) 未产出文件", language)
	}
	// 首个文件是语言主实现（client.go / client.py / client.ts）。
	return string(files[0].Code)
}

func TestGenerateGoShape(t *testing.T) {
	code := generateForTest(t, LanguageGo)
	required := []string{
		"// Code generated by ailuo sdkgen. DO NOT EDIT.",
		"package campus",
		"type Client struct {",
		"func NewClient(baseURL string) *Client",
		"func (c *Client) invoke(ctx context.Context, capabilityID string, input any) (json.RawMessage, error)",
		`"/api/v1/capabilities/"+url.PathEscape(capabilityID)+"/invoke"`,
		// 输入类型：string → string，可选 integer → 指针，date-time → time.Time
		// （gofmt 对齐列宽不固定，字段名与 json tag 分开断言）
		"type BusStopsSearchInput struct {",
		"Query",
		`json:"query"`,
		"Limit",
		`json:"limit,omitempty"`,
		"type BusJourneysSearchInput struct {",
		"OriginStopID",
		`json:"origin_stop_id"`,
		"DestinationStopID",
		`json:"destination_stop_id"`,
		"DepartAfter",
		`json:"depart_after,omitempty"`,
		// 方法名与 capability ID 绑定
		"func (c *Client) BusStopsSearch(ctx context.Context, input BusStopsSearchInput) (json.RawMessage, error) {",
		`return c.invoke(ctx, "campus.bus.stops.search", input)`,
		`return c.invoke(ctx, "campus.bus.journeys.search", input)`,
	}
	for _, want := range required {
		if !strings.Contains(code, want) {
			t.Errorf("Go 生成代码缺少 %q\n---\n%s", want, code)
		}
	}
}

func TestGeneratePythonShape(t *testing.T) {
	code := generateForTest(t, LanguagePython)
	required := []string{
		"# Code generated by ailuo sdkgen. DO NOT EDIT.",
		"class Client:",
		"def _invoke(self, capability_id: str, payload: Any) -> Any:",
		"f\"{self._base_url}/api/v1/capabilities/{capability_id}/invoke\"",
		"@dataclass\nclass BusStopsSearchInput:",
		"    query: str",
		"    limit: Optional[int] = None",
		"@dataclass\nclass BusJourneysSearchInput:",
		"    origin_stop_id: str",
		"    destination_stop_id: str",
		"    depart_after: Optional[datetime] = None",
		"def bus_stops_search(client: Client, input: BusStopsSearchInput) -> Any:",
		`return client._invoke("campus.bus.stops.search", input)`,
	}
	for _, want := range required {
		if !strings.Contains(code, want) {
			t.Errorf("Python 生成代码缺少 %q\n---\n%s", want, code)
		}
	}
}

func TestGenerateGoCompiles(t *testing.T) {
	// 生成代码必须可独立编译：写临时模块并 go build。
	// 验证 import 不依赖内核 internal 包（仅标准库）。
	dir := t.TempDir()
	files, err := Generate(json.RawMessage(campusExtensions), Options{Language: LanguageGo, PackageID: "campus"})
	if err != nil {
		t.Fatal(err)
	}
	if err := writeGoModule(t, dir, files); err != nil {
		t.Fatalf("写临时模块: %v", err)
	}
	if output, err := runGo(t, dir, "build", "./..."); err != nil {
		t.Fatalf("生成 SDK 编译失败: %v\n%s", err, output)
	}
}

func TestGeneratePythonCompiles(t *testing.T) {
	// 生成的 Python SDK 必须可导入（compileall 编译检查）。
	dir := t.TempDir()
	files, err := Generate(json.RawMessage(campusExtensions), Options{Language: LanguagePython, PackageID: "campus"})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		path := filepath.Join(dir, f.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, f.Code, 0644); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command("python", "-m", "compileall", "-q", dir)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("python compileall 失败: %v\n%s", err, output)
	}
}
