package loader_test

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/projectluojia/AI-Luo-Man-ga/contracts/pkg/capability"
	"github.com/projectluojia/AI-Luo-Man-ga/internal/adapters/packagesource"
	"github.com/projectluojia/AI-Luo-Man-ga/internal/kernel/contracts"
	"github.com/projectluojia/AI-Luo-Man-ga/internal/kernel/loader"
	"github.com/projectluojia/AI-Luo-Man-ga/internal/kernel/registry"
	"github.com/projectluojia/AI-Luo-Man-ga/internal/kernel/runtime"
	"github.com/projectluojia/AI-Luo-Man-ga/internal/kernel/runtime/runtimetest"
	"github.com/projectluojia/AI-Luo-Man-ga/package-manager/pkg/packagefmt"
)

const zeroDeclarationGoSource = "//go:build wasip1\n\n" +
	"package main\n\n" +
	"import (\n\t\"encoding/json\"\n\t\"io\"\n\t\"os\"\n)\n\n" +
	"func hello(args HelloArgs) (json.RawMessage, error) {\n" +
	"\treturn json.Marshal(map[string]string{\"message\": \"hello, \" + args.Name})\n" +
	"}\n\n" +
	"type HelloArgs struct {\n" +
	"\tName string \x60json:\"name\"\x60\n" +
	"}\n\n" +
	"type requestEnvelope struct {\n" +
	"\tCapabilityID string \x60json:\"capability_id\"\x60\n" +
	"\tPayload json.RawMessage \x60json:\"payload\"\x60\n" +
	"}\n\n" +
	"type resultEnvelope struct {\n" +
	"\tOK bool \x60json:\"ok\"\x60\n" +
	"\tResult json.RawMessage \x60json:\"result,omitempty\"\x60\n" +
	"\tCode string \x60json:\"code,omitempty\"\x60\n" +
	"}\n\n" +
	"func main() {\n" +
	"\tinput, err := io.ReadAll(os.Stdin)\n" +
	"\tif err != nil {\n" +
	"\t\tWriteEnvelope(resultEnvelope{Code: \"internal\"})\n" +
	"\t\treturn\n" +
	"\t}\n" +
	"\tvar request requestEnvelope\n" +
	"\tif err := json.Unmarshal(input, &request); err != nil || request.CapabilityID != \"autogen.test.hello\" {\n" +
	"\t\tWriteEnvelope(resultEnvelope{Code: \"invalid_argument\"})\n" +
	"\t\treturn\n" +
	"\t}\n" +
	"\tvar args HelloArgs\n" +
	"\tif err := json.Unmarshal(request.Payload, &args); err != nil {\n" +
	"\t\tWriteEnvelope(resultEnvelope{Code: \"invalid_argument\"})\n" +
	"\t\treturn\n" +
	"\t}\n" +
	"\tresult, err := hello(args)\n" +
	"\tif err != nil {\n" +
	"\t\tWriteEnvelope(resultEnvelope{Code: \"internal\"})\n" +
	"\t\treturn\n" +
	"\t}\n" +
	"\tWriteEnvelope(resultEnvelope{OK: true, Result: result})\n" +
	"}\n\n" +
	"func WriteEnvelope(envelope resultEnvelope) {\n" +
	"\t_ = json.NewEncoder(os.Stdout).Encode(envelope)\n" +
	"}\n"

// TestAutoGeneratedCapabilityRunsThroughDispatcher 验证作者侧自动提取、构建和
// Loader/Dispatcher 运行链路；packagefmt 自身的单元测试不依赖 Core。
func TestAutoGeneratedCapabilityRunsThroughDispatcher(t *testing.T) {
	ctx := context.Background()
	sourceDir := filepath.Join(t.TempDir(), "autogen.test")
	if err := os.MkdirAll(sourceDir, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sourceDir, "main.go"), []byte(zeroDeclarationGoSource), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sourceDir, "go.mod"), []byte("module autogen-e2e\n\ngo 1.26\n"), 0o640); err != nil {
		t.Fatal(err)
	}
	capabilities, buildTool, err := packagefmt.AutoExtract(ctx, sourceDir)
	if err != nil {
		t.Fatalf("AutoExtract: %v", err)
	}
	if buildTool != packagefmt.BuildToolGoWasm || len(capabilities) != 1 {
		t.Fatalf("extraction = %s %#v", buildTool, capabilities)
	}
	manifest, _, err := packagefmt.ManifestFromCapabilities("autogen.test", "1.0.0", capabilities)
	if err != nil {
		t.Fatal(err)
	}
	if err := packagefmt.Build(ctx, sourceDir, manifest, []packagefmt.BuildSpec{{Tool: buildTool}}); err != nil {
		t.Fatalf("Build: %v", err)
	}
	if err := packagesource.VerifyHostedProtocol(ctx, sourceDir, manifest); err != nil {
		t.Fatalf("VerifyHostedProtocol: %v", err)
	}
	artifactPath := filepath.Join(sourceDir, "main.wasm")
	artifact, err := os.ReadFile(artifactPath)
	if err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256(artifact)
	host, err := loader.NewWasmHost(loader.WasmHostConfig{
		ReadArtifact: func(context.Context, loader.Manifest) ([]byte, error) {
			return os.ReadFile(artifactPath)
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	manager, err := loader.New(host)
	if err != nil {
		t.Fatal(err)
	}
	runtimeID := "autogen.test.main"
	if err := manager.Register(ctx, loader.Manifest{
		ID: runtimeID, Version: manifest.Version, Mode: loader.ModeHosted,
		Role: loader.RoleProvider, LockedDigest: hex.EncodeToString(digest[:]),
	}); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := manager.Shutdown(context.Background()); err != nil {
			t.Errorf("Shutdown: %v", err)
		}
	})
	reg := registry.New()
	extracted := capabilities[0]
	if err := reg.Register(registry.CapabilityRegistration{
		Spec: capability.CapabilitySpec{
			ID: extracted.ID, Version: manifest.Version,
			InputSchemaJSON: string(extracted.InputSchema), SideEffect: capability.SideEffectRead,
		},
		Handler: manager.Handler(runtimeID),
	}); err != nil {
		t.Fatal(err)
	}
	policy := runtimetest.NewStaticAppPolicy()
	policy.Enable(manifest.ID, extracted.ID)
	dispatcher := runtime.NewDispatcher(reg, policy, runtime.DispatcherConfig{})
	result, err := dispatcher.InvokeCapability(ctx, contracts.RequestContext{
		AppID: manifest.ID, EchoID: "echo-1", RequestID: "request-1",
		UserID: "user-1", Deadline: time.Now().Add(time.Minute),
	}, extracted.ID, json.RawMessage(`{"name":"Ada"}`))
	if err != nil {
		t.Fatalf("InvokeCapability: %v", err)
	}
	if string(result) != `{"message":"hello, Ada"}` {
		t.Fatalf("result = %s", result)
	}
}
