// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: executor.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AcceptedProtocolVersions []string               `protobuf:"bytes,1,rep,name=accepted_protocol_versions,json=acceptedProtocolVersions,proto3" json:"accepted_protocol_versions,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetAcceptedProtocolVersions() []string {
	if x != nil {
		return x.AcceptedProtocolVersions
	}
	return nil
}

type HealthResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Ready                     bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	SupportedProtocolVersions []string               `protobuf:"bytes,3,rep,name=supported_protocol_versions,json=supportedProtocolVersions,proto3" json:"supported_protocol_versions,omitempty"`
	StatusCode                string                 `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetSupportedProtocolVersions() []string {
	if x != nil {
		return x.SupportedProtocolVersions
	}
	return nil
}

func (x *HealthResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

type ExecutorFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EchoId   string                 `protobuf:"bytes,1,opt,name=echo_id,json=echoId,proto3" json:"echo_id,omitempty"`
	RunId    string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ExecutorFrame_StartRun
	//	*ExecutorFrame_CapabilityCall
	//	*ExecutorFrame_CapabilityResult
	//	*ExecutorFrame_OutputDelta
	//	*ExecutorFrame_FinalResult
	//	*ExecutorFrame_RunFailure
	//	*ExecutorFrame_CancelRun
	//	*ExecutorFrame_RunAccepted
	//	*ExecutorFrame_ResourceUsage
	Body          isExecutorFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorFrame) Reset() {
	*x = ExecutorFrame{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorFrame) ProtoMessage() {}

func (x *ExecutorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorFrame.ProtoReflect.Descriptor instead.
func (*ExecutorFrame) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorFrame) GetEchoId() string {
	if x != nil {
		return x.EchoId
	}
	return ""
}

func (x *ExecutorFrame) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutorFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ExecutorFrame) GetBody() isExecutorFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ExecutorFrame) GetStartRun() *StartRun {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_StartRun); ok {
			return x.StartRun
		}
	}
	return nil
}

func (x *ExecutorFrame) GetCapabilityCall() *CapabilityCall {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_CapabilityCall); ok {
			return x.CapabilityCall
		}
	}
	return nil
}

func (x *ExecutorFrame) GetCapabilityResult() *CapabilityResult {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_CapabilityResult); ok {
			return x.CapabilityResult
		}
	}
	return nil
}

func (x *ExecutorFrame) GetOutputDelta() *OutputDelta {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_OutputDelta); ok {
			return x.OutputDelta
		}
	}
	return nil
}

func (x *ExecutorFrame) GetFinalResult() *FinalResult {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_FinalResult); ok {
			return x.FinalResult
		}
	}
	return nil
}

func (x *ExecutorFrame) GetRunFailure() *RunFailure {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_RunFailure); ok {
			return x.RunFailure
		}
	}
	return nil
}

func (x *ExecutorFrame) GetCancelRun() *CancelRun {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_CancelRun); ok {
			return x.CancelRun
		}
	}
	return nil
}

func (x *ExecutorFrame) GetRunAccepted() *RunAccepted {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_RunAccepted); ok {
			return x.RunAccepted
		}
	}
	return nil
}

func (x *ExecutorFrame) GetResourceUsage() *ResourceUsage {
	if x != nil {
		if x, ok := x.Body.(*ExecutorFrame_ResourceUsage); ok {
			return x.ResourceUsage
		}
	}
	return nil
}

type isExecutorFrame_Body interface {
	isExecutorFrame_Body()
}

type ExecutorFrame_StartRun struct {
	StartRun *StartRun `protobuf:"bytes,10,opt,name=start_run,json=startRun,proto3,oneof"`
}

type ExecutorFrame_CapabilityCall struct {
	CapabilityCall *CapabilityCall `protobuf:"bytes,11,opt,name=capability_call,json=capabilityCall,proto3,oneof"`
}

type ExecutorFrame_CapabilityResult struct {
	CapabilityResult *CapabilityResult `protobuf:"bytes,12,opt,name=capability_result,json=capabilityResult,proto3,oneof"`
}

type ExecutorFrame_OutputDelta struct {
	OutputDelta *OutputDelta `protobuf:"bytes,13,opt,name=output_delta,json=outputDelta,proto3,oneof"`
}

type ExecutorFrame_FinalResult struct {
	FinalResult *FinalResult `protobuf:"bytes,14,opt,name=final_result,json=finalResult,proto3,oneof"`
}

type ExecutorFrame_RunFailure struct {
	RunFailure *RunFailure `protobuf:"bytes,15,opt,name=run_failure,json=runFailure,proto3,oneof"`
}

type ExecutorFrame_CancelRun struct {
	CancelRun *CancelRun `protobuf:"bytes,16,opt,name=cancel_run,json=cancelRun,proto3,oneof"`
}

type ExecutorFrame_RunAccepted struct {
	RunAccepted *RunAccepted `protobuf:"bytes,17,opt,name=run_accepted,json=runAccepted,proto3,oneof"`
}

type ExecutorFrame_ResourceUsage struct {
	ResourceUsage *ResourceUsage `protobuf:"bytes,18,opt,name=resource_usage,json=resourceUsage,proto3,oneof"`
}

func (*ExecutorFrame_StartRun) isExecutorFrame_Body() {}

func (*ExecutorFrame_CapabilityCall) isExecutorFrame_Body() {}

func (*ExecutorFrame_CapabilityResult) isExecutorFrame_Body() {}

func (*ExecutorFrame_OutputDelta) isExecutorFrame_Body() {}

func (*ExecutorFrame_FinalResult) isExecutorFrame_Body() {}

func (*ExecutorFrame_RunFailure) isExecutorFrame_Body() {}

func (*ExecutorFrame_CancelRun) isExecutorFrame_Body() {}

func (*ExecutorFrame_RunAccepted) isExecutorFrame_Body() {}

func (*ExecutorFrame_ResourceUsage) isExecutorFrame_Body() {}

type StartRun struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	InputPayload       *Payload               `protobuf:"bytes,2,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`
	Capabilities       []*Capability          `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxSteps           uint32                 `protobuf:"varint,7,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`
	ProtocolVersion    string                 `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MaxCapabilityCalls uint32                 `protobuf:"varint,9,opt,name=max_capability_calls,json=maxCapabilityCalls,proto3" json:"max_capability_calls,omitempty"`
	TraceId            string                 `protobuf:"bytes,16,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentSpanId       string                 `protobuf:"bytes,17,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ParentRunId        string                 `protobuf:"bytes,18,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	ContextPayload     *Payload               `protobuf:"bytes,19,opt,name=context_payload,json=contextPayload,proto3" json:"context_payload,omitempty"`
	MaxExecutionUnits  uint64                 `protobuf:"varint,20,opt,name=max_execution_units,json=maxExecutionUnits,proto3" json:"max_execution_units,omitempty"`
	MaxOutputBytes     uint64                 `protobuf:"varint,21,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	MaxCostMicrousd    uint64                 `protobuf:"varint,22,opt,name=max_cost_microusd,json=maxCostMicrousd,proto3" json:"max_cost_microusd,omitempty"`
	ExecutorConfig     *Payload               `protobuf:"bytes,23,opt,name=executor_config,json=executorConfig,proto3" json:"executor_config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartRun) Reset() {
	*x = StartRun{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun) ProtoMessage() {}

func (x *StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun.ProtoReflect.Descriptor instead.
func (*StartRun) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *StartRun) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StartRun) GetInputPayload() *Payload {
	if x != nil {
		return x.InputPayload
	}
	return nil
}

func (x *StartRun) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *StartRun) GetMaxSteps() uint32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *StartRun) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *StartRun) GetMaxCapabilityCalls() uint32 {
	if x != nil {
		return x.MaxCapabilityCalls
	}
	return 0
}

func (x *StartRun) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StartRun) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *StartRun) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *StartRun) GetContextPayload() *Payload {
	if x != nil {
		return x.ContextPayload
	}
	return nil
}

func (x *StartRun) GetMaxExecutionUnits() uint64 {
	if x != nil {
		return x.MaxExecutionUnits
	}
	return 0
}

func (x *StartRun) GetMaxOutputBytes() uint64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *StartRun) GetMaxCostMicrousd() uint64 {
	if x != nil {
		return x.MaxCostMicrousd
	}
	return 0
}

func (x *StartRun) GetExecutorConfig() *Payload {
	if x != nil {
		return x.ExecutorConfig
	}
	return nil
}

type RunAccepted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunAccepted) Reset() {
	*x = RunAccepted{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAccepted) ProtoMessage() {}

func (x *RunAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAccepted.ProtoReflect.Descriptor instead.
func (*RunAccepted) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *RunAccepted) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type ResourceUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionUnits uint64                 `protobuf:"varint,1,opt,name=execution_units,json=executionUnits,proto3" json:"execution_units,omitempty"`
	CostMicrousd   uint64                 `protobuf:"varint,2,opt,name=cost_microusd,json=costMicrousd,proto3" json:"cost_microusd,omitempty"`
	Retries        uint32                 `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceUsage) GetExecutionUnits() uint64 {
	if x != nil {
		return x.ExecutionUnits
	}
	return 0
}

func (x *ResourceUsage) GetCostMicrousd() uint64 {
	if x != nil {
		return x.CostMicrousd
	}
	return 0
}

func (x *ResourceUsage) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type Capability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	InputSchemaJson string                 `protobuf:"bytes,5,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *Capability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Capability) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

type CapabilityCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityCall) Reset() {
	*x = CapabilityCall{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityCall) ProtoMessage() {}

func (x *CapabilityCall) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityCall.ProtoReflect.Descriptor instead.
func (*CapabilityCall) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CapabilityCall) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *CapabilityCall) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type CapabilityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityResult) Reset() {
	*x = CapabilityResult{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityResult) ProtoMessage() {}

func (x *CapabilityResult) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityResult.ProtoReflect.Descriptor instead.
func (*CapabilityResult) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CapabilityResult) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *CapabilityResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CapabilityResult) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *CapabilityResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CapabilityResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *Payload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OutputDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Payload               `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputDelta) Reset() {
	*x = OutputDelta{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputDelta) ProtoMessage() {}

func (x *OutputDelta) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputDelta.ProtoReflect.Descriptor instead.
func (*OutputDelta) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *OutputDelta) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type FinalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Payload               `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalResult) Reset() {
	*x = FinalResult{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResult) ProtoMessage() {}

func (x *FinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResult.ProtoReflect.Descriptor instead.
func (*FinalResult) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *FinalResult) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RunFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFailure) Reset() {
	*x = RunFailure{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFailure) ProtoMessage() {}

func (x *RunFailure) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFailure.ProtoReflect.Descriptor instead.
func (*RunFailure) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *RunFailure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type CancelRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRun) Reset() {
	*x = CancelRun{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRun) ProtoMessage() {}

func (x *CancelRun) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRun.ProtoReflect.Descriptor instead.
func (*CancelRun) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *CancelRun) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x11ailuo.executor.v1\"S\n" +
	"\rHealthRequest\x12<\n" +
	"\x1aaccepted_protocol_versions\x18\x01 \x03(\tR\x18acceptedProtocolVersionsJ\x04\b\x02\x10\x03\"\x8d\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12>\n" +
	"\x1bsupported_protocol_versions\x18\x03 \x03(\tR\x19supportedProtocolVersions\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\tR\n" +
	"statusCodeJ\x04\b\x02\x10\x03\"\xdc\x05\n" +
	"\rExecutorFrame\x12\x17\n" +
	"\aecho_id\x18\x01 \x01(\tR\x06echoId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12:\n" +
	"\tstart_run\x18\n" +
	" \x01(\v2\x1b.ailuo.executor.v1.StartRunH\x00R\bstartRun\x12L\n" +
	"\x0fcapability_call\x18\v \x01(\v2!.ailuo.executor.v1.CapabilityCallH\x00R\x0ecapabilityCall\x12R\n" +
	"\x11capability_result\x18\f \x01(\v2#.ailuo.executor.v1.CapabilityResultH\x00R\x10capabilityResult\x12C\n" +
	"\foutput_delta\x18\r \x01(\v2\x1e.ailuo.executor.v1.OutputDeltaH\x00R\voutputDelta\x12C\n" +
	"\ffinal_result\x18\x0e \x01(\v2\x1e.ailuo.executor.v1.FinalResultH\x00R\vfinalResult\x12@\n" +
	"\vrun_failure\x18\x0f \x01(\v2\x1d.ailuo.executor.v1.RunFailureH\x00R\n" +
	"runFailure\x12=\n" +
	"\n" +
	"cancel_run\x18\x10 \x01(\v2\x1c.ailuo.executor.v1.CancelRunH\x00R\tcancelRun\x12C\n" +
	"\frun_accepted\x18\x11 \x01(\v2\x1e.ailuo.executor.v1.RunAcceptedH\x00R\vrunAccepted\x12I\n" +
	"\x0eresource_usage\x18\x12 \x01(\v2 .ailuo.executor.v1.ResourceUsageH\x00R\rresourceUsageB\x06\n" +
	"\x04body\"\xca\x05\n" +
	"\bStartRun\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12?\n" +
	"\rinput_payload\x18\x02 \x01(\v2\x1a.ailuo.executor.v1.PayloadR\finputPayload\x12A\n" +
	"\fcapabilities\x18\x04 \x03(\v2\x1d.ailuo.executor.v1.CapabilityR\fcapabilities\x12\x1b\n" +
	"\tmax_steps\x18\a \x01(\rR\bmaxSteps\x12)\n" +
	"\x10protocol_version\x18\b \x01(\tR\x0fprotocolVersion\x120\n" +
	"\x14max_capability_calls\x18\t \x01(\rR\x12maxCapabilityCalls\x12\x19\n" +
	"\btrace_id\x18\x10 \x01(\tR\atraceId\x12$\n" +
	"\x0eparent_span_id\x18\x11 \x01(\tR\fparentSpanId\x12\"\n" +
	"\rparent_run_id\x18\x12 \x01(\tR\vparentRunId\x12C\n" +
	"\x0fcontext_payload\x18\x13 \x01(\v2\x1a.ailuo.executor.v1.PayloadR\x0econtextPayload\x12.\n" +
	"\x13max_execution_units\x18\x14 \x01(\x04R\x11maxExecutionUnits\x12(\n" +
	"\x10max_output_bytes\x18\x15 \x01(\x04R\x0emaxOutputBytes\x12*\n" +
	"\x11max_cost_microusd\x18\x16 \x01(\x04R\x0fmaxCostMicrousd\x12C\n" +
	"\x0fexecutor_config\x18\x17 \x01(\v2\x1a.ailuo.executor.v1.PayloadR\x0eexecutorConfigJ\x04\b\x03\x10\x04J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10\"8\n" +
	"\vRunAccepted\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\"w\n" +
	"\rResourceUsage\x12'\n" +
	"\x0fexecution_units\x18\x01 \x01(\x04R\x0eexecutionUnits\x12#\n" +
	"\rcost_microusd\x18\x02 \x01(\x04R\fcostMicrousd\x12\x18\n" +
	"\aretries\x18\x03 \x01(\rR\aretries\"\x98\x01\n" +
	"\n" +
	"Capability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x05 \x01(\tR\x0finputSchemaJson\"q\n" +
	"\x0eCapabilityCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12#\n" +
	"\rcapability_id\x18\x02 \x01(\tR\fcapabilityId\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\"\xd1\x01\n" +
	"\x10CapabilityResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12#\n" +
	"\rcapability_id\x18\x02 \x01(\tR\fcapabilityId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"@\n" +
	"\aPayload\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"C\n" +
	"\vOutputDelta\x124\n" +
	"\apayload\x18\x01 \x01(\v2\x1a.ailuo.executor.v1.PayloadR\apayload\"C\n" +
	"\vFinalResult\x124\n" +
	"\apayload\x18\x01 \x01(\v2\x1a.ailuo.executor.v1.PayloadR\apayload\"X\n" +
	"\n" +
	"RunFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"#\n" +
	"\tCancelRun\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\xaf\x01\n" +
	"\x0fExecutorRuntime\x12M\n" +
	"\x03Run\x12 .ailuo.executor.v1.ExecutorFrame\x1a .ailuo.executor.v1.ExecutorFrame(\x010\x01\x12M\n" +
	"\x06Health\x12 .ailuo.executor.v1.HealthRequest\x1a!.ailuo.executor.v1.HealthResponseBLZJgithub.com/projectluojia/AI-Luo-Man-ga/contracts/pkg/executorv1;executorv1b\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_executor_proto_goTypes = []any{
	(*HealthRequest)(nil),    // 0: ailuo.executor.v1.HealthRequest
	(*HealthResponse)(nil),   // 1: ailuo.executor.v1.HealthResponse
	(*ExecutorFrame)(nil),    // 2: ailuo.executor.v1.ExecutorFrame
	(*StartRun)(nil),         // 3: ailuo.executor.v1.StartRun
	(*RunAccepted)(nil),      // 4: ailuo.executor.v1.RunAccepted
	(*ResourceUsage)(nil),    // 5: ailuo.executor.v1.ResourceUsage
	(*Capability)(nil),       // 6: ailuo.executor.v1.Capability
	(*CapabilityCall)(nil),   // 7: ailuo.executor.v1.CapabilityCall
	(*CapabilityResult)(nil), // 8: ailuo.executor.v1.CapabilityResult
	(*Payload)(nil),          // 9: ailuo.executor.v1.Payload
	(*OutputDelta)(nil),      // 10: ailuo.executor.v1.OutputDelta
	(*FinalResult)(nil),      // 11: ailuo.executor.v1.FinalResult
	(*RunFailure)(nil),       // 12: ailuo.executor.v1.RunFailure
	(*CancelRun)(nil),        // 13: ailuo.executor.v1.CancelRun
}
var file_executor_proto_depIdxs = []int32{
	3,  // 0: ailuo.executor.v1.ExecutorFrame.start_run:type_name -> ailuo.executor.v1.StartRun
	7,  // 1: ailuo.executor.v1.ExecutorFrame.capability_call:type_name -> ailuo.executor.v1.CapabilityCall
	8,  // 2: ailuo.executor.v1.ExecutorFrame.capability_result:type_name -> ailuo.executor.v1.CapabilityResult
	10, // 3: ailuo.executor.v1.ExecutorFrame.output_delta:type_name -> ailuo.executor.v1.OutputDelta
	11, // 4: ailuo.executor.v1.ExecutorFrame.final_result:type_name -> ailuo.executor.v1.FinalResult
	12, // 5: ailuo.executor.v1.ExecutorFrame.run_failure:type_name -> ailuo.executor.v1.RunFailure
	13, // 6: ailuo.executor.v1.ExecutorFrame.cancel_run:type_name -> ailuo.executor.v1.CancelRun
	4,  // 7: ailuo.executor.v1.ExecutorFrame.run_accepted:type_name -> ailuo.executor.v1.RunAccepted
	5,  // 8: ailuo.executor.v1.ExecutorFrame.resource_usage:type_name -> ailuo.executor.v1.ResourceUsage
	9,  // 9: ailuo.executor.v1.StartRun.input_payload:type_name -> ailuo.executor.v1.Payload
	6,  // 10: ailuo.executor.v1.StartRun.capabilities:type_name -> ailuo.executor.v1.Capability
	9,  // 11: ailuo.executor.v1.StartRun.context_payload:type_name -> ailuo.executor.v1.Payload
	9,  // 12: ailuo.executor.v1.StartRun.executor_config:type_name -> ailuo.executor.v1.Payload
	9,  // 13: ailuo.executor.v1.OutputDelta.payload:type_name -> ailuo.executor.v1.Payload
	9,  // 14: ailuo.executor.v1.FinalResult.payload:type_name -> ailuo.executor.v1.Payload
	2,  // 15: ailuo.executor.v1.ExecutorRuntime.Run:input_type -> ailuo.executor.v1.ExecutorFrame
	0,  // 16: ailuo.executor.v1.ExecutorRuntime.Health:input_type -> ailuo.executor.v1.HealthRequest
	2,  // 17: ailuo.executor.v1.ExecutorRuntime.Run:output_type -> ailuo.executor.v1.ExecutorFrame
	1,  // 18: ailuo.executor.v1.ExecutorRuntime.Health:output_type -> ailuo.executor.v1.HealthResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	file_executor_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecutorFrame_StartRun)(nil),
		(*ExecutorFrame_CapabilityCall)(nil),
		(*ExecutorFrame_CapabilityResult)(nil),
		(*ExecutorFrame_OutputDelta)(nil),
		(*ExecutorFrame_FinalResult)(nil),
		(*ExecutorFrame_RunFailure)(nil),
		(*ExecutorFrame_CancelRun)(nil),
		(*ExecutorFrame_RunAccepted)(nil),
		(*ExecutorFrame_ResourceUsage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
